import type { Metadata } from "next";
import "./globals.css";
import SideBar from "@/components/layouts/sideBar";
import { instrumentSans } from "@/lib/fonts";
import Header from "@/components/layouts/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSans.className} flex h-screen flex-col p-4 sm:flex-row`}
      >
        <Header />
        <SideBar />
        {children}
      </body>
    </html>
  );
}
